### ISSUE TITLE
Got my first crash!

### ISSUE THREAD

**Issue by kidwellj** [bear-rsg/experiences-of-landscape-workers#30]
Trying to login via iPad (second device) using PWA (add to home screen already complete). Not entirely sure what caused this - was pasting password on iPad from bitwarden. But there was no way to get out of this screen without force close and reopen.

![2021-02-22_jkipad_2520](https://user-images.githubusercontent.com/790736/108742398-934ad600-752f-11eb-85c7-300dd9b2825c.png)

**Comment by kidwellj** [comment]
FYI - I think this was an attempt to login using my BHAM credentials (accidentally pasted rather than app credentials)

**Comment by mike-allaway** [comment]
Interesting - I've managed to log into multiple devices with the same account and it works as expected, so it may be caused by what you said about logging in with BHAM credentials, which is normal behaviour.

Also in terms of the forced close/reopen as there's no way to navigate away from this page, when the website is live it will show a custom error page, which includes the main navigation, which will solve this problem. It's currently set to 'debug/dev' mode so we get more information error messages (like this one!) but note that error pages (including other types) will have nicer error messages when live :)
